platform :ios, '10.0'
use_frameworks!

target 'Movies' do
    pod 'RxSwift', '6.0.0-rc.1'
    pod 'RxRelay', '6.0.0-rc.1'
    pod 'RxCocoa', '6.0.0-rc.1'
end

target 'MoviesTests' do
    pod 'RxBlocking', '6.0.0-rc.1'
    pod 'RxTest', '6.0.0-rc.1'
end